# frozen_string_literal: true

# Export CLACKY_ prefixed environment variables to their standard names
# This allows external services and libraries that expect standard names like
# OPENAI_API_KEY, ANTHROPIC_API_KEY, etc. to work with CLACKY_OPENAI_API_KEY

# Mapping of CLACKY_ prefix variables to their standard names
CLACKY_PREFIX_MAPPINGS = {
  'CLACKY_OPENAI_API_KEY' => 'OPENAI_API_KEY',
  'CLACKY_ANTHROPIC_API_KEY' => 'ANTHROPIC_API_KEY',
  'CLACKY_STRIPE_PUBLISHABLE_KEY' => 'STRIPE_PUBLISHABLE_KEY',
  'CLACKY_STRIPE_SECRET_KEY' => 'STRIPE_SECRET_KEY',
  'CLACKY_STRIPE_WEBHOOK_SECRET' => 'STRIPE_WEBHOOK_SECRET',
  'CLACKY_ASSEMBLYAI_API_KEY' => 'ASSEMBLYAI_API_KEY',
  'CLACKY_POSTFORME_API_KEY' => 'POSTFORME_API_KEY',
  'CLACKY_RAILWAY_API_KEY' => 'RAILWAY_API_KEY',
  'CLACKY_PUBLIC_HOST' => 'PUBLIC_HOST',
  'CLACKY_EMAIL_SMTP_ADDRESS' => 'EMAIL_SMTP_ADDRESS',
  'CLACKY_EMAIL_SMTP_PORT' => 'EMAIL_SMTP_PORT',
  'CLACKY_EMAIL_SMTP_USERNAME' => 'EMAIL_SMTP_USERNAME',
  'CLACKY_EMAIL_API_KEY' => 'EMAIL_SMTP_PASSWORD',
  'CLACKY_EMAIL_SMTP_DOMAIN' => 'EMAIL_SMTP_DOMAIN',
  'CLACKY_OPENAI_BASE_URL' => 'OPENAI_BASE_URL',
  'CLACKY_OPENAI_MODEL' => 'OPENAI_MODEL',
  'CLACKY_OPENAI_ORG_ID' => 'OPENAI_ORG_ID',
  'CLACKY_IMAGE_GEN_API_KEY' => 'IMAGE_GEN_API_KEY',
  'CLACKY_IMAGE_GEN_MODEL' => 'IMAGE_GEN_MODEL',
  'CLACKY_IMAGE_GEN_SIZE' => 'IMAGE_GEN_SIZE',
  'CLACKY_SORA_MODEL' => 'SORA_MODEL',
  'CLACKY_STORAGE_BUCKET_ENDPOINT' => 'STORAGE_BUCKET_ENDPOINT',
  'CLACKY_STORAGE_BUCKET_ACCESS_KEY_ID' => 'STORAGE_BUCKET_ACCESS_KEY_ID',
  'CLACKY_STORAGE_BUCKET_SECRET_ACCESS_KEY' => 'STORAGE_BUCKET_SECRET_ACCESS_KEY',
  'CLACKY_STORAGE_BUCKET_REGION' => 'STORAGE_BUCKET_REGION',
  'CLACKY_STORAGE_BUCKET_NAME' => 'STORAGE_BUCKET_NAME',
  'CLACKY_CLOUDFRONT_DOMAIN' => 'CLOUDFRONT_DOMAIN',
  'CLACKY_TWITTER_BEARER_TOKEN' => 'TWITTER_BEARER_TOKEN',
  'CLACKY_TWITTER_API_KEY' => 'TWITTER_API_KEY',
  'CLACKY_TWITTER_API_SECRET' => 'TWITTER_API_SECRET',
  'CLACKY_TWITTER_ACCESS_TOKEN' => 'TWITTER_ACCESS_TOKEN',
  'CLACKY_TWITTER_ACCESS_TOKEN_SECRET' => 'TWITTER_ACCESS_TOKEN_SECRET',
  'CLACKY_FACEBOOK_ACCESS_TOKEN' => 'FACEBOOK_ACCESS_TOKEN',
  'CLACKY_FACEBOOK_APP_ID' => 'FACEBOOK_APP_ID',
  'CLACKY_FACEBOOK_APP_SECRET' => 'FACEBOOK_APP_SECRET',
  'CLACKY_INSTAGRAM_ACCESS_TOKEN' => 'INSTAGRAM_ACCESS_TOKEN',
  'CLACKY_INSTAGRAM_APP_ID' => 'INSTAGRAM_APP_ID',
  'CLACKY_INSTAGRAM_APP_SECRET' => 'INSTAGRAM_APP_SECRET',
  'CLACKY_TIKTOK_ACCESS_TOKEN' => 'TIKTOK_ACCESS_TOKEN',
  'CLACKY_TIKTOK_CLIENT_KEY' => 'TIKTOK_CLIENT_KEY',
  'CLACKY_TIKTOK_CLIENT_SECRET' => 'TIKTOK_CLIENT_SECRET',
  'CLACKY_LINKEDIN_ACCESS_TOKEN' => 'LINKEDIN_ACCESS_TOKEN',
  'CLACKY_LINKEDIN_CLIENT_ID' => 'LINKEDIN_CLIENT_ID',
  'CLACKY_LINKEDIN_CLIENT_SECRET' => 'LINKEDIN_CLIENT_SECRET',
}.freeze

# Export CLACKY_ prefixed variables to their standard names
# Only set the standard name if the CLACKY_ version exists AND the standard name doesn't already exist
CLACKY_PREFIX_MAPPINGS.each do |clacky_key, standard_key|
  clacky_value = ENV[clacky_key]
  next if clacky_value.blank?
  next if ENV.key?(standard_key) && ENV[standard_key].present?

  ENV[standard_key] = clacky_value
end

Rails.logger.info "CLACKY_ prefix exports applied: #{CLACKY_PREFIX_MAPPINGS.count} variables processed" if defined?(Rails) && Rails.logger
