require 'rails/application'

Rails.application.routes.draw do
  # Dev route to login as user 1
  get 'dev_login', to: proc { |env|
    user = User.first
    session = user.sessions.create
    cookie_hash = Rails.application.config.session_options[:cookie_options]
    # Set session cookie
    "".tap do |response|
      Rack::Response.new([], 302, {'Location' => '/', 'Set-Cookie' => "_clacky_app_session=; path=/"}).finish
    end
  }

  get 'login_as/:user_id', to: 'sessions#login_as'
  post 'login_as/:user_id', to: 'sessions#login_as'
  # Routes for subscriptions generated by controller generator
  resources :subscriptions, only: [:create]
  # End routes for subscriptions

  # Routes for pricings generated by controller generator
  resources :pricing, only: [] do
    collection { get :index }
  end
  # End routes for pricings

  # Routes for purchases generated by controller generator
  resources :purchases, only: [:create]
  # End routes for purchases

  resources :payments, only: [] do
    member do
      get :pay
      post :pay
      get :success
      get :failure
    end
  end
  post '/webhooks/stripe', to: 'payments#webhook'
  # Health check endpoint for Railway
  get "up" => "rails/health#show", as: :rails_health_check

  # Webhook routes for Postforme (API namespace)
  namespace :api do
    namespace :v1 do
      post 'postforme/webhook', to: 'postforme_webhooks#receive'
    end
  end

  # Webhook route for Poyo.ai video callbacks
  post 'poyo_webhook', to: 'poyo_webhooks#video_callback'

  # Social Media Dashboard
  resources :social_media_dashboard, only: [:index] do
    post :sync_all, on: :collection
    get :available_profiles, on: :collection
    post :connect_profile, on: :collection
  end
  # Social Account Connections
  resources :social_account_connections, only: [:index] do
    post :update_api_key, on: :collection
    get :available_profiles, on: :collection
    post :connect_profile, on: :collection
    post :disconnect_account, on: :member
    post :share_to_social_media, on: :collection
  end

  # Social Posts Management
  resources :social_posts do
    member do
      post 'share_now'
      get 'results'
      get 'analytics'
      get 'preview'
    end
    collection do
      get 'list'
    end
  end

  # Social Account Feeds
  get 'social_account_feeds/:account_id', to: 'social_posts#account_feed', as: :social_account_feed

  # PWA routes
  get '/manifest.json', to: 'pwa#manifest', defaults: { format: :json }
  get '/service-worker.js', to: 'pwa#service_worker', defaults: { format: :js }
  # Root path
  root "home#index"

  # Dashboard route (singular)
  get 'dashboard', to: 'dashboards#index'

  # API routes
  namespace :api do
    namespace :v1 do
      # Voice API endpoints
      post 'voice/transcribe', to: 'voice#transcribe'
      post 'voice/stream', to: 'voice_stream#transcribe_and_stream'
      post 'voice/chat', to: 'voice#chat'
      get 'voice/health', to: 'voice#health'
      get 'voice/stream/health', to: 'voice_stream#health'
      
      # AI Chat API endpoints
      post 'ai_chat/stream_message', to: 'ai_chat#stream_message'
      post 'ai_chat/send_message', to: 'ai_chat#send_message'
      post 'ai_chat/create_conversation', to: 'ai_chat#create_conversation'
      post 'ai_chat/confirm_tool', to: 'ai_chat#confirm_tool'
      get 'ai_chat/conversations', to: 'ai_chat#conversations'
      get 'ai_chat/messages/:conversation_id', to: 'ai_chat#messages'
      
      # Workflow API endpoints
      post 'workflows', to: 'workflows#create'
      get 'workflows', to: 'workflows#index'
      get 'workflows/:id', to: 'workflows#show'
    end
  end

  # Authentication routes
  get 'sign_in', to: 'sessions#new', as: :new_user_session
  post 'sign_in', to: 'sessions#create', as: :user_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_user_session
  
  # Additional session routes
  get 'devices', to: 'sessions#devices', as: :devices_session
  get 'sessions/:id', to: 'sessions#show', as: :session
  
  get 'sign_up', to: 'registrations#new', as: :new_user_registration
  post 'sign_up', to: 'registrations#create', as: :user_registration
  
  get 'forgot_password', to: 'identity/password_resets#new', as: :new_user_password
  post 'forgot_password', to: 'identity/password_resets#create', as: :user_password
  get 'reset_password/:sid', to: 'identity/password_resets#edit', as: :edit_user_password
  patch 'reset_password/:sid', to: 'identity/password_resets#update'
  
  get 'confirm_email/:sid', to: 'identity/email_verifications#show', as: :user_email_verification
  post 'confirm_email/:sid', to: 'identity/email_verifications#confirm'
  get 'resend_confirmation', to: 'identity/email_verifications#new', as: :new_user_email_verification
  get 'resend_confirmation/:sid', to: 'identity/email_verifications#resend', as: :identity_email_verification
  
  # Identity email management
  get 'emails', to: 'identity/emails#edit', as: :edit_identity_email
  patch 'emails', to: 'identity/emails#update'
  
  # Convenience aliases for navbar
  get 'sign_in', to: 'sessions#new', as: :sign_in
  get 'sign_up', to: 'registrations#new', as: :sign_up
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out

  # Admin routes
  namespace :admin do
    resources :payments, only: [:index, :show]
    root "dashboard#index"
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :administrators, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :destroy]
    resources :accounts, only: [:index, :show, :edit, :update]
    resources :admin_oplogs, only: [:index, :show]
    
    # Dedicated password change route for current admin
    get 'password/change', to: 'accounts#change_password', as: :change_password
    patch 'password/change', to: 'accounts#update_password'
  end

  # Policy Settings
  resources :policy_settings, only: [:index, :update] do
    collection do
      post :reset
    end
  end

  # Application routes
  resource :profile, only: [:show, :edit] do
    member do
      get 'edit_password', to: 'profiles#edit_password'
      patch 'update_password', to: 'profiles#update_password'
    end
  end
  resources :dashboards, only: [:index] do
    member do
      post 'respond'
    end
  end
  resources :campaigns do
    member do
      post 'add_content'
      post 'remove_content'
      post 'duplicate'
      get 'analytics'
      post 'schedule_all'
      post 'publish_now'
    end
    collection do
      post 'bulk_actions'
      get 'export'
    end
  end
  resources :contents do
    member do
      get 'preview'
      get 'optimize'
      post 'approve'
      post 'reject'
    end
  end
  resources :social_accounts
  resources :scheduled_posts do
    member do
      post 'publish_now'
      post 'optimize'
      post 'add_note'
      get 'predictions'
    end
    collection do
      post 'bulk_update'
      post 'batch_schedule'
      get 'optimal_times'
      get 'engagement_predictions'
      get 'scheduling_analytics'
    end
  end
  resources :voice_commands, only: [:index, :show, :create]
  resources :performance_metrics, only: [:index]
  
  # Calendar Management System
  resources :calendar, only: [:index] do
    collection do
      post 'optimize'
      post 'reschedule'
      get 'suggestions'
      post 'bulk_schedule'
    end
  end
  
  # AI & Voice features routes
  resources :ai_chat, only: [:index, :show, :create] do
    collection do
      post 'send_message'
      post 'suggest_content'
    end
  end
  
  # AI Autopilot
  resources :ai_autopilot, only: [:index] do
    collection do
      post 'toggle'
      post 'generate_content'
      post 'analyze_engagement'
      get 'logs'
    end
  end
  
  # AI Marketing Strategy Analyzer
  resources :ai_marketing_strategy, only: [:index] do
    collection do
      post 'analyze'
      post 'generate_report'
      post 'ask_ai'
    end
  end
  
  resources :voice_controller, only: [] do
    collection do
      post 'generate_voice'
      post 'speech_to_text'
      get 'get_voices'
      post 'save_voice_settings'
    end
  end
  
  # Content & Scheduling features routes
  resources :content_creation, only: [:index] do
    collection do
      post 'create_draft'
      patch 'update_draft'
      post 'generate_content'
      post 'generate_ideas'
      post 'generate_image'
      post 'generate_video'
      post 'edit_image'
    end
    member do
      post 'publish_content'
      post 'schedule_content'
    end
  end
  
  resources :prompt_templates, only: [:index, :create, :update, :destroy]
  
  # Draft Management System
  resources :drafts do
    member do
      post 'convert_to_content'
      post 'duplicate'
    end
    collection do
      post 'bulk_actions'
      get 'search'
    end
  end
  
  # Content Template System
  resources :content_templates, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      post 'duplicate'
      post 'process'
      post 'preview'
    end
    collection do
      get 'popular'
      get 'by_category'
    end
  end
  
  # Content Suggestions System
  resources :content_suggestions, only: [:index, :show, :create, :update, :destroy]
  
  # Automation Rules
  resources :automation_rules do
    member do
      post 'toggle'
      post 'execute_now'
    end
    collection do
      get 'statistics'
    end
  end
  
  # Scheduled Posts - Auto-Response Triggers
  resources :auto_response_triggers do
    member do
      post 'toggle_status'
      post 'test_trigger'
      post 'execute_now'
    end
    collection do
      get 'statistics'
    end
  end
  
  # Scheduled Posts - Scheduled AI Tasks
  resources :scheduled_ai_tasks do
    member do
      post 'toggle_status'
      post 'test_trigger'
      post 'execute_now'
    end
    collection do
      get 'statistics'
    end
  end
  
  # Auto-Response Executions (optional)
  resources :trigger_executions, only: [:index, :show] do
    collection do
      get 'statistics'
    end
  end
  
  # Task Executions (optional)
  resources :task_executions, only: [:index, :show] do
    collection do
      get 'statistics'
    end
  end
  
  # Engagement Analytics
  resources :engagement_analytics, only: [:index]
  
  # Trend Analysis
  resources :trend_analyses, only: [:index] do
    collection do
      post 'generate_report'
      get 'predictions'
    end
  end
  
  # Voice Commands
  resources :voice_commands, only: [:index, :show, :create] do
    member do
      post 'execute'
    end
  end
  
  # Voice Settings
  resource :voice_settings, only: [:show, :edit, :update]
  
  # Publish Queue
  resources :publish_queues, only: [:index] do
    member do
      post 'process'
      post 'retry'
    end
    collection do
      get 'stats'
    end
  end
  
  # Zapier Webhooks
  resources :zapier_webhooks, only: [:index, :show, :create, :update, :destroy]
  
  # Content Publishing
  resources :publish_queues, only: [:index, :show]
  
  # Admin/Background Job Management
  resource :admin_oplogs, only: [:index, :show]
  
  # Postforme Integration
  resources :postforme_webhooks, only: [:create]
  
  # Pages
  get 'pages/features', to: 'pages#features'
  get 'pages/pricing', to: 'pages#pricing'
  get 'pages/about', to: 'pages#about'
  
  # Additional user routes
  get 'social-media-dashboard', to: 'social_media_dashboard#index'
  get 'connect-accounts', to: 'social_account_connections#index'
  get 'engagement-analytics', to: 'engagement_analytics#index'
  get 'trends', to: 'trend_analyses#index'
  get 'automation', to: 'automation_rules#index'
  
end
