require 'rails/application'

Rails.application.routes.draw do
  # Routes for workflows generated by controller generator
  resources :workflows, only: [:index, :new, :create, :show, :destroy]
  # End routes for workflows

  # Routes for waitlists generated by controller generator
  # Waitlist for launch notifications
  post 'api/waitlist', to: 'waitlist#create', as: :api_waitlist
  resources :waitlists, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # End routes for waitlists

  # Postforme OAuth callback
  get 'auth/postforme/callback', to: 'social_account_connections#oauth_callback'
  post 'auth/postforme/callback', to: 'social_account_connections#oauth_callback'
  
  # Pricing page route
  get 'subscription', to: 'pricing#index', as: :subscription
  resources :pricing, only: [] do
    collection { get :index }
  end
  # End routes for pricings

  # Routes for subscriptions (create only)
  resources :subscriptions, only: [:create]
  # End routes for subscriptions

  # Promo codes validation
  post 'api/promo_codes/validate', to: 'api/promo_codes#validate', as: :validate_promo_code
  # End routes for promo_codes

  # Routes for purchases generated by controller generator
  resources :purchases, only: [:create]
  # End routes for purchases

  resources :payments, only: [] do
    member do
      get :pay
      post :pay
      get :success
      get :failure
    end
  end
  post '/webhooks/stripe', to: 'payments#webhook'
  # Health check endpoint for Railway
  get "up" => "rails/health#show", as: :rails_health_check

  # Emergency migration fix (no auth required)
  get 'migration-fix', to: 'migration_fix#run'

  # Webhook routes for Postforme (API namespace)
  namespace :api do
    namespace :v1 do
      post 'postforme/webhook', to: 'postforme_webhooks#receive'
    end
  end

  # Webhook route for Atlas Cloud video callbacks
  post 'atlas_cloud_webhook', to: 'atlas_cloud_webhooks#video_callback'

  # Social Media Dashboard
  resources :social_media_dashboard, only: [:index] do
    post :sync_all, on: :collection
    get :available_profiles, on: :collection
    post :connect_profile, on: :collection
  end
  # Social Account Connections
  resources :social_account_connections, only: [:index] do
    post :update_api_key, on: :collection
    get :available_profiles, on: :collection
    post :connect_profile, on: :collection
    post :disconnect_account, on: :member
    post :share_to_social_media, on: :collection
    get :initiate_oauth, on: :collection
  end

  # Social Posts Management
  resources :social_posts do
    member do
      post 'share_now'
      get 'results'
      get 'analytics'
      get 'preview'
    end
    collection do
      get 'list'
    end
  end

  # Social Account Feeds
  get 'social_account_feeds/:account_id', to: 'social_posts#account_feed', as: :social_account_feed

  # PWA routes
  get '/manifest.json', to: 'pwa#manifest', defaults: { format: :json }
  get '/service-worker.js', to: 'pwa#service_worker', defaults: { format: :js }
  # Root path
  root "home#index"

  # ActionCable WebSocket mount
  mount ActionCable.server => '/cable'

  # Dashboard route (singular)
  get 'dashboard', to: 'dashboards#index'

  # Webhooks
  post 'webhooks/postforme', to: 'webhooks/postforme_webhooks#receive'

  # API routes
  namespace :api do
    namespace :v1 do
      # Workflow API endpoints
      post 'workflows', to: 'workflows#create'
      get 'workflows', to: 'workflows#index'
      get 'workflows/:id', to: 'workflows#show'

      # Campaign Health API endpoints
      get 'campaign_health', to: 'campaign_health#index'
      get 'campaign_health/:id', to: 'campaign_health#show'

      # Agency Dashboard API endpoints
      get 'agency/dashboard', to: 'agency#dashboard'
      get 'agency/clients/:id', to: 'agency#client'
      get 'agency/campaigns', to: 'agency#campaigns'
      get 'agency/trending', to: 'agency#trending'
      get 'agency/viral-context', to: 'agency#viral_context'
      get 'agency/costs', to: 'agency#costs'
    end
  end

  # Simple Chat API endpoint
  post '/api/v1/chat', to: 'chat#create'
  post '/api/v1/transcribe', to: 'chat#transcribe'
  post '/api/v1/speak', to: 'chat#speak'

  # Otto-Pilot AI Chat
  namespace :api do
    namespace :v1 do
      post 'otto/chat', to: 'otto#chat'
      post 'voice_settings', to: 'voice_settings#create'
      post 'otto/execute', to: 'otto#execute'
      get 'otto/draft_status', to: 'otto#draft_status'
      get 'otto/history', to: 'otto#history'
      post 'otto/clear', to: 'otto#clear'
      post 'otto/transcribe', to: 'otto#transcribe'
      post 'otto/start_onboarding', to: 'otto#start_onboarding'
      post 'otto/dismiss_onboarding', to: 'otto#dismiss_onboarding'
      get 'otto/brand_profile_status', to: 'otto#brand_profile_status'
      post 'otto/complete_onboarding', to: 'otto#complete_onboarding'
    end
  end

  # Authentication routes
  get 'sign_in', to: 'sessions#new', as: :new_user_session
  post 'sign_in', to: 'sessions#create', as: :user_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_user_session
  
  # Additional session routes
  get 'devices', to: 'sessions#devices', as: :devices_session
  get 'sessions/:id', to: 'sessions#show', as: :session
  
  get 'sign_up', to: 'registrations#new', as: :new_user_registration
  post 'sign_up', to: 'registrations#create', as: :user_registration
  
  get 'forgot_password', to: 'identity/password_resets#new', as: :new_user_password
  post 'forgot_password', to: 'identity/password_resets#create', as: :user_password
  get 'reset_password/:sid', to: 'identity/password_resets#edit', as: :edit_user_password
  patch 'reset_password/:sid', to: 'identity/password_resets#update'
  
  get 'confirm_email/:sid', to: 'identity/email_verifications#show', as: :user_email_verification
  post 'confirm_email/:sid', to: 'identity/email_verifications#confirm'
  get 'resend_confirmation', to: 'identity/email_verifications#new', as: :new_user_email_verification
  get 'resend_confirmation/:sid', to: 'identity/email_verifications#resend', as: :identity_email_verification
  
  # Identity email management
  get 'emails', to: 'identity/emails#edit', as: :edit_identity_email
  patch 'emails', to: 'identity/emails#update'
  
  # Brand Profile routes
  post 'profile/brand_profile', to: 'profiles#update_brand_profile', as: :update_brand_profile
  
  # Convenience aliases for navbar
  get 'sign_in', to: 'sessions#new', as: :sign_in
  get 'sign_up', to: 'registrations#new', as: :sign_up
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out

  # Admin routes
  namespace :admin do
    resources :site_settings
    resources :payments, only: [:index, :show]
    root "dashboard#index"
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    resources :administrators, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :destroy] do
      member do
        post :verify
        post :unverify
      end
    end
    resources :accounts, only: [:index, :show, :edit, :update]
    resources :admin_oplogs, only: [:index, :show]
    
    # Dedicated password change route for current admin
    get 'password/change', to: 'accounts#change_password', as: :change_password
    patch 'password/change', to: 'accounts#update_password'
    
    # Emergency migration fix endpoint (no auth, secret key protected)
    get 'migration-fix', to: 'migration_fix#run'
  end

  # Agency Dashboard routes
  namespace :agency do
    root "dashboard#index"
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/client/:id', to: 'dashboard#client', as: :client_dashboard
    get 'dashboard/campaigns', to: 'dashboard#campaigns', as: :agency_campaigns
    get 'dashboard/trending', to: 'dashboard#trending', as: :agency_trending
    get 'dashboard/trending/:client_id', to: 'dashboard#trending', as: :client_trending
    get 'dashboard/costs', to: 'dashboard#costs', as: :agency_costs
  end

  # Policy Settings
  resources :policy_settings, only: [:index, :update] do
    collection do
      post :reset
    end
  end

  # AI Assistant routes
  resources :assistants, only: [:index, :show, :destroy] do
    post :chat
    post :complete_step
    delete :clear
  end

  # AI Content Generation routes
  resources :ai_content, only: [:index, :show, :new, :create] do
    collection do
      post :generate
    end
    member do
      post :regenerate
      post :update_content
    end
  end
  # End routes for AI content

  # Autopilot routes
  resources :autopilot, only: [:index, :show] do
    collection do
      post :start
      post :stop
      get :status
      get :history
    end
  end
  # End autopilot routes

  # Voice Settings routes
  resources :voice_settings, only: [:show, :edit, :update, :create]

  # Application routes
  resource :profile, only: [:show, :edit] do
    member do
      get 'edit_password', to: 'profiles#edit_password'
      patch 'update_password', to: 'profiles#update_password'
    end
  end
  resources :dashboards, only: [:index] do
    member do
      post 'respond'
    end
  end
  # Campaign Builder routes
  resources :campaign_builder, only: [:index] do
    collection do
      get :select_template
      get :customize_form
      post :preview
      post :create
      post :ai_customize
    end
  end
  
  resources :campaigns do
    member do
      post 'add_content'
      post 'remove_content'
      post 'duplicate'
      get 'analytics'
      post 'schedule_all'
      post 'publish_now'
    end
    collection do
      post 'bulk_actions'
      get 'export'
    end
  end
  
  # Client routes
  resources :clients
  resources :contents do
    member do
      get 'preview'
      get 'optimize'
      post 'approve'
      post 'reject'
      post 'duplicate'
      post 'generate_variation'
    end
  end
  resources :social_accounts
  resources :scheduled_posts do
    member do
      post 'publish_now'
      post 'optimize'
      post 'add_note'
      get 'predictions'
    end
    collection do
      post 'bulk_update'
      post 'batch_schedule'
      get 'optimal_times'
      get 'engagement_predictions'
      get 'scheduling_analytics'
    end
  end
  resources :voice_commands, only: [:index, :show, :create]
  resources :performance_metrics, only: [:index]
  
  # Calendar Management System
  resources :calendar, only: [:index] do
    collection do
      post 'optimize'
      post 'reschedule'
      get 'suggestions'
      post 'bulk_schedule'
      post 'bulk_cancel'
      post 'bulk_reschedule'
      get 'post_details'
      get 'show_post'
    end
    member do
      get 'edit_post'
      patch 'update_post'
      post 'cancel_post'
      post 'retry_post'
      post 'publish_now'
    end
  end
  
  # AI Marketing Strategy Analyzer
  resources :ai_marketing_strategy do
    collection do
      post 'analyze'
      post 'generate_report'
      post 'ask_ai'
      get 'history'
      post 'execute'
      get 'trend'
    end
  end
  
  resources :voice_controller, only: [] do
    collection do
      post 'generate_voice'
      post 'speech_to_text'
      get 'get_voices'
      post 'save_voice_settings'
    end
  end
  
  # Content & Scheduling features routes
  resources :content_creation, only: [:index] do
    collection do
      post 'create_draft'
      patch 'update_draft'
      post 'generate_content'
      post 'generate_ideas'
      post 'generate_image'
      post 'generate_video'
      post 'edit_image'
    end
    member do
      post 'publish_content'
      post 'schedule_content'
    end
  end
  
  # Test Anthropic API
  get '/test_anthropic', to: 'test_anthropic#test'
  
  resources :prompt_templates, only: [:index, :create, :update, :destroy]
  
  # Draft Management System
  get '/drafts', to: redirect('/contents')
  resources :drafts do
    member do
      post 'convert_to_content'
      post 'duplicate'
      post 'retry_video_status'
    end
    collection do
      post 'bulk_actions'
      get 'search'
    end
  end

  # Route for DraftContent preview
  resources :draft_contents, only: [] do
    member do
      get 'preview'
    end
  end
  
  # Content Template System
  resources :content_templates, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    member do
      post 'duplicate'
      post 'process'
      post 'preview'
    end
    collection do
      get 'popular'
      get 'by_category'
    end
  end
  
  # Content Suggestions System
  resources :content_suggestions, only: [:index, :show, :create, :update, :destroy]
  
  # Content Approval Routes (email-based approval system)
  get 'content_approvals/:token', to: 'content_approvals#show', as: :content_approval
  post 'content_approvals/:token', to: 'content_approvals#update'
  
  # Automation Rules
  resources :automation_rules do
    member do
      post 'toggle_status'
      post 'test_rule'
    end
    collection do
      get 'statistics'
      post 'create_from_template'
      post 'bulk_actions'
    end
  end
  
  # Scheduled Posts - Auto-Response Triggers
  resources :auto_response_triggers do
    member do
      post 'toggle_status'
      post 'test_trigger'
      post 'execute_now'
    end
    collection do
      get 'statistics'
    end
  end
  
  # Scheduled Posts - Scheduled AI Tasks
  resources :scheduled_ai_tasks do
    member do
      post 'toggle_status'
      post 'test_trigger'
      post 'execute_now'
    end
    collection do
      get 'statistics'
    end
  end
  
  # Auto-Response Executions (optional)
  resources :trigger_executions, only: [:index, :show] do
    collection do
      get 'statistics'
    end
  end
  
  # Task Executions (optional)
  resources :task_executions, only: [:index, :show] do
    collection do
      get 'statistics'
    end
  end
  
  # Engagement Analytics
  resources :engagement_analytics, only: [:index]
  
  # Trend Analysis
  resources :trend_analyses, only: [:index] do
    collection do
      post 'generate_report'
      get 'predictions'
    end
  end
  
  # Voice Commands
  resources :voice_commands, only: [:index, :show, :create] do
    member do
      post 'execute'
    end
  end
  
  # Voice Settings
  resource :voice_settings, only: [:show, :edit, :update]
  
  # Publish Queue
  resources :publish_queues, only: [:index] do
    member do
      post 'process'
      post 'retry'
    end
    collection do
      get 'stats'
    end
  end
  
  # Content Publishing
  resources :publish_queues, only: [:index, :show]
  
  # Admin/Background Job Management
  resource :admin_oplogs, only: [:index, :show]
  
  # Postforme Integration
  resources :postforme_webhooks, only: [:create]

  # Postforme Analytics Dashboard
  resources :postforme_analytics, only: [:index] do
    collection do
      post :refresh
    end
  end
  
  # Pages
  get 'pages/features', to: 'pages#features'
  get 'pages/pricing', to: 'pages#pricing'
  get 'pages/about', to: 'pages#about'
  get 'pages/faq', to: 'pages#faq'
  get 'pages/terms_of_service', to: 'pages#terms_of_service'
  get 'pages/privacy_policy', to: 'pages#privacy_policy'

  # Sitemap
  get 'sitemap.xml', to: 'sitemaps#index', defaults: { format: :xml }, as: :sitemap
  get 'sitemaps/:sitemap', to: 'sitemaps#show', constraints: { format: :xml }

  # Additional user routes
  get 'social-media-dashboard', to: 'social_media_dashboard#index'
  get 'connect-accounts', to: 'social_account_connections#index'
  get 'engagement-analytics', to: 'engagement_analytics#index'
  get 'trends', to: 'trend_analyses#index'
  get 'automation', to: 'automation_rules#index'
  
  # Workflows
  resources :workflows do
    member do
      post 'run'
    end
  end
  
end
