class Identity::EmailVerificationsController < ApplicationController
  before_action :authenticate_user!, only: :create

  before_action :set_user, only: :show

  def new
    if current_user.email_was_generated?
      redirect_to profile_path, alert: "Your email was generated by the system and cannot be verified. Please update it with a valid email address."
    else
      send_email_verification
      redirect_to profile_path, notice: "We sent a verification email to your email address"
    end
  end

  def show
    @user.update! verified: true
    redirect_to profile_path, notice: "Thank you for verifying your email address"
  end

  def create
    if current_user.email_was_generated?
      redirect_to profile_path, alert: "Your email was generated by the system and cannot be verified. Please update it with a valid email address."; return
    end
    send_email_verification
    redirect_to profile_path, notice: "We sent a verification email to your email address"
  end

  private

  def set_user
    @user = User.find_by_token_for!(:email_verification, params[:sid])
  rescue StandardError
    redirect_to edit_identity_email_path, alert: "That email verification link is invalid"
  end

  def send_email_verification
    user = Current.user
    signed_id = user.generate_token_for(:email_verification)
    app_name = Rails.application.config.x.appname
    verify_url = identity_email_verification_url(sid: signed_id)

    html_content = <<~HTML
      <div style="font-family:sans-serif;max-width:560px;margin:0 auto;padding:40px;">
        <h1 style="font-size:24px;font-weight:700;">Email Verification</h1>
        <p>Hey there,</p>
        <p>This is to confirm that <strong>#{user.email}</strong> is the email you want to use on your account.</p>
        <p>Click the link below to verify your email address:</p>
        <p><a href="#{verify_url}" style="background:#2563eb;color:#fff;padding:12px 24px;text-decoration:none;border-radius:6px;display:inline-block;">Yes, use this email for my account</a></p>
        <p style="color:#888;font-size:13px;">If you didn't request this, you can safely ignore this email.</p>
      </div>
    HTML

    SendgridEmailService.send_email(
      to: user.email,
      subject: "[#{app_name}] Verify your email",
      html_content: html_content
    )
  end
end
