# frozen_string_literal: true

# Safe migration to ensure ai_conversations and ai_messages tables have proper primary keys
# This addresses "No unique index found for id" errors without dropping data
class FixAiTablesPrimaryKeys < ActiveRecord::Migration[7.2]
  def up
    # Only run if tables exist but might be missing primary keys
    if table_exists?(:ai_conversations) && !index_exists?(:ai_conversations, :id, unique: true)
      begin
        # Add primary key if missing - Rails should auto-create this but just in case
        execute "ALTER TABLE ai_conversations ADD PRIMARY KEY (id)" rescue nil
        Rails.logger.info "Fixed: Added primary key to ai_conversations"
      rescue => e
        Rails.logger.error "ai_conversations primary key fix failed: #{e.message}"
      end
    end
    
    if table_exists?(:ai_messages) && !index_exists?(:ai_messages, :id, unique: true)
      begin
        execute "ALTER TABLE ai_messages ADD PRIMARY KEY (id)" rescue nil
        Rails.logger.info "Fixed: Added primary key to ai_messages"
      rescue => e
        Rails.logger.error "ai_messages primary key fix failed: #{e.message}"
      end
    end
    
    # Also ensure the id columns exist and are bigint
    if table_exists?(:ai_conversations) && column_exists?(:ai_conversations, :id)
      begin
        # Make sure id is bigserial (auto-incrementing bigint) for PostgreSQL
        execute "ALTER TABLE ai_conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY" rescue nil
      rescue => e
        Rails.logger.info "ai_conversations id identity: #{e.message}"
      end
    end
    
    if table_exists?(:ai_messages) && column_exists?(:ai_messages, :id)
      begin
        execute "ALTER TABLE ai_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY" rescue nil
      rescue => e
        Rails.logger.info "ai_messages id identity: #{e.message}"
      end
    end
  end

  def down
    # No-op
  end
end
